// sets.js — Japanese Pokémon TCG expansion dataset for CardPriceCheck.
// Plain script (no modules): defines the single global constant CPC_JP_SETS.
//
// NOTE: compiled from general knowledge. Release dates are approximate (where
// only the month is known, the 1st of the month is used) and minor sets may be
// missing or slightly misdated — this list is user-editable, feel free to
// correct or extend it. Entries are sorted by Japanese release date, ascending.
//
// Fields:
//   code    - lowercase set code, unique across the array (official Japanese
//             code where one exists, otherwise a short slug); matched against
//             listing titles with word-boundary regexes.
//   name    - common English set name
//   jaName  - Japanese set name
//   era     - one of: Original, Neo, e-Card, ADV, PCG, DP, DPt, LEGEND, BW,
//             XY, SM, Sword & Shield, Scarlet & Violet
//   release - Japanese release date, YYYY-MM-DD

const CPC_JP_SETS = [
  { code: 'base', name: 'Base Set', jaName: '拡張パック 第1弾', era: 'Original', release: '1996-10-20' },
  { code: 'jungle', name: 'Jungle', jaName: 'ポケモンジャングル', era: 'Original', release: '1997-03-01' },
  { code: 'fossil', name: 'Fossil', jaName: '化石の秘密', era: 'Original', release: '1997-06-01' },
  { code: 'rocket', name: 'Team Rocket', jaName: 'ロケット団', era: 'Original', release: '1997-11-01' },
  { code: 'vending1', name: 'Vending Series 1', jaName: '拡張シート 第1弾', era: 'Original', release: '1998-02-01' },
  { code: 'vending2', name: 'Vending Series 2', jaName: '拡張シート 第2弾', era: 'Original', release: '1998-05-01' },
  { code: 'gym1', name: 'Leaders\' Stadium', jaName: 'ポケモンジム リーダーズスタジアム', era: 'Original', release: '1998-08-01' },
  { code: 'vending3', name: 'Vending Series 3', jaName: '拡張シート 第3弾', era: 'Original', release: '1998-10-01' },
  { code: 'gym2', name: 'Challenge from the Darkness', jaName: '闇からの挑戦', era: 'Original', release: '1999-04-01' },
  { code: 'southern', name: 'Southern Islands', jaName: 'サザンアイランド', era: 'Original', release: '1999-07-01' },
  { code: 'neo1', name: 'Gold, Silver, to a New World...', jaName: '金、銀、新世界へ…', era: 'Neo', release: '1999-12-01' },
  { code: 'neo2', name: 'Crossing the Ruins...', jaName: '遺跡をこえて…', era: 'Neo', release: '2000-04-01' },
  { code: 'neo3', name: 'Awakening Legends', jaName: 'めざめる伝説', era: 'Neo', release: '2000-07-01' },
  { code: 'neo4', name: 'Darkness, and to Light...', jaName: '闇、そして光へ…', era: 'Neo', release: '2001-04-01' },
  { code: 'pokemonvs', name: 'Pokémon VS', jaName: 'ポケモンカード★VS', era: 'Neo', release: '2001-07-01' },
  { code: 'web', name: 'Pokémon Web', jaName: 'ポケモンカード★web', era: 'Neo', release: '2001-08-01' },
  { code: 'e1', name: 'Base Expansion Pack', jaName: '基本拡張パック 第1弾', era: 'e-Card', release: '2001-12-01' },
  { code: 'e2', name: 'The Town on No Map', jaName: '地図にない町', era: 'e-Card', release: '2002-03-01' },
  { code: 'e3', name: 'Wind from the Sea', jaName: '海からの風', era: 'e-Card', release: '2002-05-01' },
  { code: 'e4', name: 'Split Earth', jaName: '裂けた大地', era: 'e-Card', release: '2002-08-01' },
  { code: 'e5', name: 'Mysterious Mountains', jaName: '神秘なる山', era: 'e-Card', release: '2002-11-01' },
  { code: 'adv1', name: 'ADV Expansion Pack', jaName: '拡張パック', era: 'ADV', release: '2003-01-31' },
  { code: 'adv2', name: 'Miracle of the Desert', jaName: '砂漠の奇跡', era: 'ADV', release: '2003-04-01' },
  { code: 'adv3', name: 'Rulers of the Heavens', jaName: '天空の覇者', era: 'ADV', release: '2003-07-01' },
  { code: 'magmavsaqua', name: 'Magma VS Aqua: Two Ambitions', jaName: 'マグマVSアクア ふたつの野望', era: 'ADV', release: '2003-10-01' },
  { code: 'adv4', name: 'Undone Seal', jaName: 'とかれた封印', era: 'ADV', release: '2003-12-01' },
  { code: 'pcg1', name: 'Flight of Legends', jaName: '伝説の飛翔', era: 'PCG', release: '2004-01-29' },
  { code: 'pcg2', name: 'Rocket Gang\'s Counterattack', jaName: 'ロケット団の逆襲', era: 'PCG', release: '2004-08-01' },
  { code: 'pcg3', name: 'Clash of the Blue Sky', jaName: '蒼空の激突', era: 'PCG', release: '2004-12-01' },
  { code: 'pcg4', name: 'Golden Sky, Silvery Ocean', jaName: '金の空、銀の海', era: 'PCG', release: '2005-06-01' },
  { code: 'pcg5', name: 'Holon Research Tower', jaName: 'ホロンの研究塔', era: 'PCG', release: '2005-08-01' },
  { code: 'pcg6', name: 'Mirage\'s Forest', jaName: 'ミラージュの森', era: 'PCG', release: '2005-12-01' },
  { code: 'pcg7', name: 'Holon Phantom', jaName: 'ホロンの幻影', era: 'PCG', release: '2006-03-01' },
  { code: 'pcg8', name: 'Miracle Crystal', jaName: 'きせきの結晶', era: 'PCG', release: '2006-04-01' },
  { code: 'pcg9', name: 'Offense and Defense of the Furthest Ends', jaName: 'さいはての攻防', era: 'PCG', release: '2006-07-01' },
  { code: 'wcp', name: 'World Champions Pack', jaName: 'ワールドチャンピオンズパック', era: 'PCG', release: '2006-08-01' },
  { code: 'dp1', name: 'Space-Time Creation', jaName: '時空の創造', era: 'DP', release: '2006-10-01' },
  { code: 'dp2', name: 'Secret of the Lakes', jaName: '湖の秘密', era: 'DP', release: '2007-03-01' },
  { code: 'dp3', name: 'Shining Darkness', jaName: 'ひかる闇', era: 'DP', release: '2007-06-01' },
  { code: 'dp4', name: 'Moonlit Pursuit / Dawn Dash', jaName: '月光の追跡・夜明けの疾走', era: 'DP', release: '2007-11-01' },
  { code: 'dp5', name: 'Temple of Anger / Cry from the Mysterious', jaName: '怒りの神殿・秘境の叫び', era: 'DP', release: '2008-03-01' },
  { code: 'dp6', name: 'Intense Fight in the Destroyed Sky', jaName: '破空の激闘', era: 'DP', release: '2008-07-01' },
  { code: 'dpt1', name: 'Galactic\'s Conquest', jaName: 'ギンガの覇道', era: 'DPt', release: '2008-10-01' },
  { code: 'dpt2', name: 'Bonds to the End of Time', jaName: '時の果ての絆', era: 'DPt', release: '2008-12-01' },
  { code: 'dpt3', name: 'Beat of the Frontier', jaName: 'フロンティアの鼓動', era: 'DPt', release: '2009-03-01' },
  { code: 'dpt4', name: 'Advent of Arceus', jaName: 'アルセウス光臨', era: 'DPt', release: '2009-07-01' },
  { code: 'l1', name: 'HeartGold & SoulSilver Collection', jaName: 'ハートゴールドコレクション・ソウルシルバーコレクション', era: 'LEGEND', release: '2009-10-09' },
  { code: 'l2', name: 'Reviving Legends', jaName: 'よみがえる伝説', era: 'LEGEND', release: '2010-02-01' },
  { code: 'll', name: 'Lost Link', jaName: 'ロストリンク', era: 'LEGEND', release: '2010-04-01' },
  { code: 'l3', name: 'Clash at the Summit', jaName: '頂上大激突', era: 'LEGEND', release: '2010-07-01' },
  { code: 'bw1', name: 'Black Collection / White Collection', jaName: 'ブラックコレクション・ホワイトコレクション', era: 'BW', release: '2010-12-17' },
  { code: 'bw2', name: 'Red Collection', jaName: 'レッドコレクション', era: 'BW', release: '2011-06-17' },
  { code: 'bw3', name: 'Psycho Drive / Hail Blizzard', jaName: 'サイコドライブ・ヘイルブリザード', era: 'BW', release: '2011-09-16' },
  { code: 'bw4', name: 'Dark Rush', jaName: 'ダークラッシュ', era: 'BW', release: '2011-12-16' },
  { code: 'ds', name: 'Dragon Selection', jaName: 'ドラゴンセレクション', era: 'BW', release: '2012-01-01' },
  { code: 'bw5', name: 'Dragon Blast / Dragon Blade', jaName: 'リューズブラスト・リューノブレード', era: 'BW', release: '2012-03-16' },
  { code: 'bw6', name: 'Cold Flare / Freeze Bolt', jaName: 'コールドフレア・フリーズボルト', era: 'BW', release: '2012-07-13' },
  { code: 'bw7', name: 'Plasma Gale', jaName: 'プラズマゲイル', era: 'BW', release: '2012-09-14' },
  { code: 'bw8', name: 'Spiral Force / Thunder Knuckle', jaName: 'ラセンフォース・ライデンナックル', era: 'BW', release: '2013-01-01' },
  { code: 'sc', name: 'Shiny Collection', jaName: 'シャイニーコレクション', era: 'BW', release: '2013-02-01' },
  { code: 'bw9', name: 'Megalo Cannon', jaName: 'メガロキャノン', era: 'BW', release: '2013-03-15' },
  { code: 'ebb', name: 'EX Battle Boost', jaName: 'EXバトルブースト', era: 'BW', release: '2013-07-01' },
  { code: 'xy1', name: 'Collection X / Collection Y', jaName: 'コレクションX・コレクションY', era: 'XY', release: '2013-12-13' },
  { code: 'xy2', name: 'Wild Blaze', jaName: 'ワイルドブレイズ', era: 'XY', release: '2014-03-15' },
  { code: 'xy3', name: 'Rising Fist', jaName: 'ライジングフィスト', era: 'XY', release: '2014-06-14' },
  { code: 'xy4', name: 'Phantom Gate', jaName: 'ファントムゲート', era: 'XY', release: '2014-09-13' },
  { code: 'xy5', name: 'Gaia Volcano / Tidal Storm', jaName: 'ガイアボルケーノ・タイダルストーム', era: 'XY', release: '2014-12-13' },
  { code: 'cp1', name: 'Double Crisis', jaName: 'マグマ団VSアクア団 ダブルクライシス', era: 'XY', release: '2015-01-30' },
  { code: 'xy6', name: 'Emerald Break', jaName: 'エメラルドブレイク', era: 'XY', release: '2015-03-14' },
  { code: 'xy7', name: 'Bandit Ring', jaName: 'バンデットリング', era: 'XY', release: '2015-06-20' },
  { code: 'cp2', name: 'Legendary Shine Collection', jaName: '伝説キラコレクション', era: 'XY', release: '2015-07-01' },
  { code: 'xy8', name: 'Red Flash / Blue Impact', jaName: '赤い閃光・青い衝撃', era: 'XY', release: '2015-09-26' },
  { code: 'xy9', name: 'Rage of the Broken Heavens', jaName: '破天の怒り', era: 'XY', release: '2015-12-11' },
  { code: 'cp3', name: 'PokéKyun Collection', jaName: 'ポケキュンコレクション', era: 'XY', release: '2016-01-29' },
  { code: 'xy10', name: 'Awakening Psychic King', jaName: 'めざめる超王', era: 'XY', release: '2016-03-18' },
  { code: 'xy11', name: 'Explosive Fighter / Cruel Traitor', jaName: '爆熱の闘士・冷酷の反逆者', era: 'XY', release: '2016-06-17' },
  { code: 'cp5', name: 'Mythical & Legendary Dream Shine Collection', jaName: '幻・伝説ドリームキラコレクション', era: 'XY', release: '2016-07-01' },
  { code: 'cp4', name: 'Premium Champion Pack', jaName: 'プレミアムチャンピオンパック「EX×M×BREAK」', era: 'XY', release: '2016-09-16' },
  { code: 'cp6', name: 'Expansion Pack 20th Anniversary', jaName: '拡張パック 20th Anniversary', era: 'XY', release: '2016-09-16' },
  { code: 'sm1s', name: 'Collection Sun', jaName: 'コレクション サン', era: 'SM', release: '2016-12-09' },
  { code: 'sm1m', name: 'Collection Moon', jaName: 'コレクション ムーン', era: 'SM', release: '2016-12-09' },
  { code: 'sm1plus', name: 'Strength Expansion Pack Sun & Moon', jaName: '強化拡張パック「サン&ムーン」', era: 'SM', release: '2017-01-27' },
  { code: 'sm2k', name: 'Islands Await You', jaName: 'キミを待つ島々', era: 'SM', release: '2017-03-17' },
  { code: 'sm2l', name: 'Alolan Moonlight', jaName: 'アローラの月光', era: 'SM', release: '2017-03-17' },
  { code: 'bestofxy', name: 'The Best of XY', jaName: 'THE BEST OF XY', era: 'XY', release: '2017-04-01' },
  { code: 'sm3n', name: 'Did You See the Fighting Rainbow?', jaName: '闘う虹を見たか', era: 'SM', release: '2017-06-16' },
  { code: 'sm3h', name: 'Darkness that Consumes Light', jaName: '光を喰らう闇', era: 'SM', release: '2017-06-16' },
  { code: 'sm3plus', name: 'Shining Legends', jaName: 'ひかる伝説', era: 'SM', release: '2017-07-15' },
  { code: 'sm4s', name: 'Ultradimensional Beasts', jaName: '超次元の暴獣', era: 'SM', release: '2017-09-15' },
  { code: 'sm4a', name: 'Awakened Heroes', jaName: '覚醒の勇者', era: 'SM', release: '2017-09-15' },
  { code: 'sm4plus', name: 'GX Battle Boost', jaName: 'GXバトルブースト', era: 'SM', release: '2017-10-20' },
  { code: 'sm5s', name: 'Ultra Sun', jaName: 'ウルトラサン', era: 'SM', release: '2017-12-08' },
  { code: 'sm5m', name: 'Ultra Moon', jaName: 'ウルトラムーン', era: 'SM', release: '2017-12-08' },
  { code: 'sm5plus', name: 'Ultra Force', jaName: 'ウルトラフォース', era: 'SM', release: '2018-01-19' },
  { code: 'sm6', name: 'Forbidden Light', jaName: '禁断の光', era: 'SM', release: '2018-03-02' },
  { code: 'sm6a', name: 'Dragon Storm', jaName: 'ドラゴンストーム', era: 'SM', release: '2018-04-06' },
  { code: 'sm6b', name: 'Champion Road', jaName: 'チャンピオンロード', era: 'SM', release: '2018-05-01' },
  { code: 'sm7', name: 'Charisma of the Wrecked Sky', jaName: '裂空のカリスマ', era: 'SM', release: '2018-06-01' },
  { code: 'sm7a', name: 'Thunderclap Spark', jaName: '迅雷スパーク', era: 'SM', release: '2018-07-06' },
  { code: 'sm7b', name: 'Fairy Rise', jaName: 'フェアリーライズ', era: 'SM', release: '2018-08-03' },
  { code: 'sm8', name: 'Explosive Impact', jaName: '超爆インパクト', era: 'SM', release: '2018-09-07' },
  { code: 'sm8a', name: 'Dark Order', jaName: 'ダークオーダー', era: 'SM', release: '2018-10-05' },
  { code: 'sm8b', name: 'GX Ultra Shiny', jaName: 'GXウルトラシャイニー', era: 'SM', release: '2018-11-02' },
  { code: 'sm9', name: 'Tag Bolt', jaName: 'タッグボルト', era: 'SM', release: '2018-12-07' },
  { code: 'sm9a', name: 'Night Unison', jaName: 'ナイトユニゾン', era: 'SM', release: '2019-01-11' },
  { code: 'sm9b', name: 'Full Metal Wall', jaName: 'フルメタルウォール', era: 'SM', release: '2019-02-01' },
  { code: 'sm10', name: 'Double Blaze', jaName: 'ダブルブレイズ', era: 'SM', release: '2019-03-01' },
  { code: 'sm10a', name: 'GG End', jaName: 'ジージーエンド', era: 'SM', release: '2019-04-05' },
  { code: 'sm10b', name: 'Sky Legend', jaName: 'スカイレジェンド', era: 'SM', release: '2019-04-25' },
  { code: 'sm11', name: 'Miracle Twin', jaName: 'ミラクルツイン', era: 'SM', release: '2019-05-31' },
  { code: 'sm11a', name: 'Remix Bout', jaName: 'リミックスバウト', era: 'SM', release: '2019-07-05' },
  { code: 'sm11b', name: 'Dream League', jaName: 'ドリームリーグ', era: 'SM', release: '2019-08-02' },
  { code: 'sm12', name: 'Alter Genesis', jaName: 'オルタージェネシス', era: 'SM', release: '2019-09-06' },
  { code: 'sm12a', name: 'Tag All Stars', jaName: 'タッグオールスターズ', era: 'SM', release: '2019-10-04' },
  { code: 's1w', name: 'Sword', jaName: 'ソード', era: 'Sword & Shield', release: '2019-12-06' },
  { code: 's1h', name: 'Shield', jaName: 'シールド', era: 'Sword & Shield', release: '2019-12-06' },
  { code: 's1a', name: 'VMAX Rising', jaName: 'VMAXライジング', era: 'Sword & Shield', release: '2020-02-07' },
  { code: 's2', name: 'Rebellion Crash', jaName: '反逆クラッシュ', era: 'Sword & Shield', release: '2020-03-06' },
  { code: 's2a', name: 'Explosive Walker', jaName: '爆炎ウォーカー', era: 'Sword & Shield', release: '2020-04-24' },
  { code: 's3', name: 'Infinity Zone', jaName: 'ムゲンゾーン', era: 'Sword & Shield', release: '2020-06-05' },
  { code: 's3a', name: 'Legendary Heartbeat', jaName: '伝説の鼓動', era: 'Sword & Shield', release: '2020-07-10' },
  { code: 's4', name: 'Astonishing Volt Tackle', jaName: '仰天のボルテッカー', era: 'Sword & Shield', release: '2020-09-18' },
  { code: 's4a', name: 'Shiny Star V', jaName: 'シャイニースターV', era: 'Sword & Shield', release: '2020-11-20' },
  { code: 's5i', name: 'Single Strike Master', jaName: '一撃マスター', era: 'Sword & Shield', release: '2021-01-22' },
  { code: 's5r', name: 'Rapid Strike Master', jaName: '連撃マスター', era: 'Sword & Shield', release: '2021-01-22' },
  { code: 's5a', name: 'Matchless Fighters', jaName: '双璧のファイター', era: 'Sword & Shield', release: '2021-03-19' },
  { code: 's6h', name: 'Silver Lance', jaName: '白銀のランス', era: 'Sword & Shield', release: '2021-04-23' },
  { code: 's6k', name: 'Jet-Black Spirit', jaName: '漆黒のガイスト', era: 'Sword & Shield', release: '2021-04-23' },
  { code: 's6a', name: 'Eevee Heroes', jaName: 'イーブイヒーローズ', era: 'Sword & Shield', release: '2021-05-28' },
  { code: 's7d', name: 'Skyscraping Perfect', jaName: '摩天パーフェクト', era: 'Sword & Shield', release: '2021-07-09' },
  { code: 's7r', name: 'Blue Sky Stream', jaName: '蒼空ストリーム', era: 'Sword & Shield', release: '2021-07-09' },
  { code: 's8', name: 'Fusion Arts', jaName: 'フュージョンアーツ', era: 'Sword & Shield', release: '2021-09-24' },
  { code: 's8a', name: '25th Anniversary Collection', jaName: '25th ANNIVERSARY COLLECTION', era: 'Sword & Shield', release: '2021-10-22' },
  { code: 's8b', name: 'VMAX Climax', jaName: 'VMAXクライマックス', era: 'Sword & Shield', release: '2021-12-03' },
  { code: 's9', name: 'Star Birth', jaName: 'スターバース', era: 'Sword & Shield', release: '2022-01-14' },
  { code: 's9a', name: 'Battle Region', jaName: 'バトルリージョン', era: 'Sword & Shield', release: '2022-02-25' },
  { code: 's10d', name: 'Time Gazer', jaName: 'タイムゲイザー', era: 'Sword & Shield', release: '2022-04-08' },
  { code: 's10p', name: 'Space Juggler', jaName: 'スペースジャグラー', era: 'Sword & Shield', release: '2022-04-08' },
  { code: 's10a', name: 'Dark Phantasma', jaName: 'ダークファンタズマ', era: 'Sword & Shield', release: '2022-05-13' },
  { code: 's10b', name: 'Pokémon GO', jaName: 'ポケモンGO', era: 'Sword & Shield', release: '2022-06-17' },
  { code: 's11', name: 'Lost Abyss', jaName: 'ロストアビス', era: 'Sword & Shield', release: '2022-07-15' },
  { code: 's11a', name: 'Incandescent Arcana', jaName: '白熱のアルカナ', era: 'Sword & Shield', release: '2022-09-02' },
  { code: 's12', name: 'Paradigm Trigger', jaName: 'パラダイムトリガー', era: 'Sword & Shield', release: '2022-10-21' },
  { code: 's12a', name: 'VSTAR Universe', jaName: 'VSTARユニバース', era: 'Sword & Shield', release: '2022-12-02' },
  { code: 'sv1s', name: 'Scarlet ex', jaName: 'スカーレットex', era: 'Scarlet & Violet', release: '2023-01-20' },
  { code: 'sv1v', name: 'Violet ex', jaName: 'バイオレットex', era: 'Scarlet & Violet', release: '2023-01-20' },
  { code: 'sv1a', name: 'Triplet Beat', jaName: 'トリプレットビート', era: 'Scarlet & Violet', release: '2023-03-10' },
  { code: 'sv2d', name: 'Clay Burst', jaName: 'クレイバースト', era: 'Scarlet & Violet', release: '2023-04-14' },
  { code: 'sv2p', name: 'Snow Hazard', jaName: 'スノーハザード', era: 'Scarlet & Violet', release: '2023-04-14' },
  { code: 'sv2a', name: 'Pokémon Card 151', jaName: 'ポケモンカード151', era: 'Scarlet & Violet', release: '2023-06-16' },
  { code: 'sv3', name: 'Ruler of the Black Flame', jaName: '黒炎の支配者', era: 'Scarlet & Violet', release: '2023-07-28' },
  { code: 'sv3a', name: 'Raging Surf', jaName: 'レイジングサーフ', era: 'Scarlet & Violet', release: '2023-09-22' },
  { code: 'sv4k', name: 'Ancient Roar', jaName: '古代の咆哮', era: 'Scarlet & Violet', release: '2023-10-27' },
  { code: 'sv4m', name: 'Future Flash', jaName: '未来の一閃', era: 'Scarlet & Violet', release: '2023-10-27' },
  { code: 'sv4a', name: 'Shiny Treasure ex', jaName: 'シャイニートレジャーex', era: 'Scarlet & Violet', release: '2023-12-01' },
  { code: 'sv5k', name: 'Wild Force', jaName: 'ワイルドフォース', era: 'Scarlet & Violet', release: '2024-01-26' },
  { code: 'sv5m', name: 'Cyber Judge', jaName: 'サイバージャッジ', era: 'Scarlet & Violet', release: '2024-01-26' },
  { code: 'sv5a', name: 'Crimson Haze', jaName: 'クリムゾンヘイズ', era: 'Scarlet & Violet', release: '2024-03-22' },
  { code: 'sv6', name: 'Mask of Change', jaName: '変幻の仮面', era: 'Scarlet & Violet', release: '2024-04-26' },
  { code: 'sv6a', name: 'Night Wanderer', jaName: 'ナイトワンダラー', era: 'Scarlet & Violet', release: '2024-06-07' },
  { code: 'sv7', name: 'Stellar Miracle', jaName: 'ステラミラクル', era: 'Scarlet & Violet', release: '2024-07-19' },
  { code: 'sv7a', name: 'Paradise Dragona', jaName: '楽園ドラゴーナ', era: 'Scarlet & Violet', release: '2024-09-13' },
  { code: 'sv8', name: 'Super Electric Breaker', jaName: '超電ブレイカー', era: 'Scarlet & Violet', release: '2024-10-18' },
  { code: 'sv8a', name: 'Terastal Festival ex', jaName: 'テラスタルフェスex', era: 'Scarlet & Violet', release: '2024-12-06' },
  { code: 'sv9', name: 'Battle Partners', jaName: 'バトルパートナーズ', era: 'Scarlet & Violet', release: '2025-01-24' },
  { code: 'sv9a', name: 'Heat Wave Arena', jaName: '熱風のアリーナ', era: 'Scarlet & Violet', release: '2025-03-14' },
  { code: 'sv10', name: 'Glory of Team Rocket', jaName: 'ロケット団の栄光', era: 'Scarlet & Violet', release: '2025-04-18' },
  { code: 'sv11b', name: 'Black Bolt', jaName: 'ブラックボルト', era: 'Scarlet & Violet', release: '2025-06-06' },
  { code: 'sv11w', name: 'White Flare', jaName: 'ホワイトフレア', era: 'Scarlet & Violet', release: '2025-06-06' },
  { code: 'm1l', name: 'Mega Brave', jaName: 'メガブレイブ', era: 'Scarlet & Violet', release: '2025-09-26' },
  { code: 'm1s', name: 'Mega Symphonia', jaName: 'メガシンフォニア', era: 'Scarlet & Violet', release: '2025-09-26' },
];
